# -*- coding: utf-8 -*-
"""Assignment_02_Task_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BwGu6TusfGyNIBYf1FLh3aDnWPOxDtg9

Task 1: Check if a Number is Even or Odd

Problem Statement: Write a Python program that:

Takes an integer input from the user.
Checks whether the number is even or odd using an if-else statement.
Displays the result accordingly.
"""

#Step 1-Assign a variable (num), where the input is taken from the user.

num=int(input('Enter a number:'))

#To check if the number is even or odd, the logic is:
#even: divisible by 2, remainder=0
#odd: indivisible by 2, remained!=0

if num%2==0:
  print(f'{num} is an even number')
else:
  print(f'{num} is an odd number')
print('end') #Marks the end of the program