# -*- coding: utf-8 -*-
"""Assignment_02_Task_02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PMiLjD6fulvgzOzsCB3WFZmQd4v2ZxJd

Task 2: Sum of Integers from 1 to 50 Using a Loop

Problem Statement: Write a Python program that:

Uses a for loop to iterate over numbers from 1 to 50.
Calculates the sum of all integers in this range.
Displays the final sum.
"""

#using for loop to iterate over numbers from 1 to 50.
for i in range (1,51):
  print(i)

sum_of_numbers = 0
for i in range(1, 51):
  sum_of_numbers += i

print(f'The sum of integers from 1 to 50 is: {sum_of_numbers}')